# Generated by Django 4.2.15 on 2024-09-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_audiofile_transcription'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='audiofile',
            unique_together={('user', 'file')},
        ),
    ]
